[platformio]
default_envs = sensor

[env]
; pioarduino fork: platform resmi PlatformIO belum menyediakan board ESP32-H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = esp32-h2-devkitm-1
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.2.3

[env:sensor]
build_src_filter = +<sensor/*.cpp>

[env:monitor]
build_src_filter = +<monitor/*.cpp>
