[platformio]
default_envs = server

[env]
; pioarduino fork: platform resmi PlatformIO belum menyediakan board ESP32-H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = esp32-h2-devkitm-1
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.2.3

[env:server]
build_src_filter = +<server/*.cpp>

[env:client]
build_src_filter = +<client/*.cpp>
