[platformio]
default_envs = node1

[env]
; pioarduino fork: platform resmi PlatformIO belum menyediakan board ESP32-H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = esp32-h2-devkitm-1
monitor_speed = 115200

[env:node1]
build_src_filter = +<node1/*.cpp>

[env:node2]
build_src_filter = +<node2/*.cpp>
