[platformio]
default_envs = c6_gateway

[env]
; pioarduino fork: platform resmi PlatformIO belum menyediakan board ESP32-H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
monitor_speed = 115200

[env:h2_node]
board = esp32-h2-devkitm-1
build_src_filter = +<h2_node/*.cpp>

[env:c6_gateway]
board = esp32-c6-devkitc-1
build_src_filter = +<c6_gateway/*.cpp>
; Thread/BLE + Wi-Fi + MQTT/HTTP melebihi partisi app default (1,25 MB)
board_build.partitions = huge_app.csv
lib_deps =
    knolleary/PubSubClient@^2.8
