[platformio]
default_envs = central

[env]
; pioarduino fork: platform resmi PlatformIO belum menyediakan board ESP32-H2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = esp32-h2-devkitm-1
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.2.3

[env:central]
build_src_filter = +<central/*.cpp>

[env:nodea]
build_src_filter = +<nodea/*.cpp>

[env:nodeb]
build_src_filter = +<nodeb/*.cpp>
